# Ex5A Numpy Fundamentals

This exercise explores Numpy arrays, including creating 1D, 2D, and 3D arrays, checking data types, using transpose, and selecting values using indexing and slicing.

In [15]:
# Importing NumPy library and giving it an alias 'np':
import numpy as np

## Array Basics

In [16]:
# Creating a variable that will store a list:
fruits = ["apple", "banana", "cherry", "date"]

print(fruits)

['apple', 'banana', 'cherry', 'date']


In [17]:
# This converts the regular list into a NumPy array
# arr_1 is 1D because it only has one row of data
arr_1 = np.array(fruits)

print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [18]:
# Shows data type:
print(arr_1.dtype)
# <U6
# U means Unicode string (text)
# 6 means the maximum string length stored in the array

<U6


In [19]:
# Creating 2D array:
arr_2 = np.array([
    [10, 11, 12],
    [13, 14, 15]
])

print(arr_2)
# It's like a table that has 2 rows and 3 columns

[[10 11 12]
 [13 14 15]]


In [20]:
# Using transpose:
print(arr_2.T)
# Turning rows into columns

[[10 13]
 [11 14]
 [12 15]]


In [21]:
arr_3 = np.array([
    [1, 3, 5],
    [2, 4, 6]
])

print(arr_3)

[[1 3 5]
 [2 4 6]]


In [22]:
# Picking specific values:
# Getting arr_3 in row 0, column 2. Row 0 is [1, 3, 5]. Column 2 in this line is 5.
# Getting arr_3 in row 0, column 2. Row 1 is [2, 4, 6]. Column 1 in this line is 4.
arr_4 = np.array([
    arr_3[0,2],
    arr_3[1,1]
])

print(arr_4)

[5 4]


In [23]:
# Creating 3D array:
arr_5 = np.ones((2, 2, 2))

print(arr_5)
# It's like 2 mini tables stacked together

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
