# Exercise 1.A NumPy: Manipulating Arrays

In [2]:
import numpy as np

## Looping Through Arrays

In [4]:
# 2D array
arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])

print(arrA)

[[11 12 13]
 [14 15 16]]


In [ ]:
# For loop goes through each dimension (each row) of arrA and multiply it by 2
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [8]:
# First for loop goes through each row in arrA
# Second one goes inside each row and grabs each value inside then multiplies it by 2
# Then prints it one at a time
for x in arrA:
    for y in x:
        print(y *2)

22
24
26
28
30
32


The first for loop goes through the first dimension of the array, so it prints one full row at a time multiplied by 2. The second loop goes deeper into the array and prints each individual value inside the row then multiplied it by 2. That's why the first loop prints rows, but the second loop prints one number per line.

In [11]:
for x in arrA:
    for y in x:
        loop_result = x * 2

print(loop_result)

# This result is different because the loop_result is using x, not y. x represents the 
# whole row, so x * 2 multiplies the whole row by 2. Since loop_result keeps getting 
# overwritten, only the last row's result is printed after the loop finishes.

[28 30 32]


## Joining and Stacking Arrays

In [ ]:
# This joins arrA with another copy of arrA
# axis=0 is the default axis so i dont have to include it
# It means stacking by rows in vertical directionso the second copy gets added underneath the first copy
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [ ]:
# axis=1 means horizontal direction so the copies were added side by side with the original
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [ ]:
# This stacks 2 copies of joined_array_1 into a new dimension
# It's not just adding rows or columns, it's creating a deeper array
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [ ]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)

# This gives a ValueError because joined_array_1 and joined_array_2 do not have the same shape
# joined_array_1 has 4 rows and 3 columns
# joined_array_2 has 2 rows and 6 columns
# np.stack() needs the arrays to have the same exact shape

ValueError: all input arrays must have the same shape

In [20]:
# This joined join_array_1 with arrA using the default axis, which is axis=0
# That means arrA gets added underneath joined_array_1
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [ ]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_2)

# This gives an error because the arrays do not have the same number of rows
# joined_array_1 has 4 rows, but arrA has 2 rows
# When using axis=1, NumPy is trying to join side by side, so the row counts must match

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [24]:
h_stack = np.hstack((arrA, arrA))
# hstack joins arrays horizontally, meaning side by side.

v_stack = np.vstack((arrA, arrA))
# vstack joins arrays vertically, meaning one underneath the other.

d_stack = np.dstack((arrA, arrA))
# dstack stacks arrays by depth, creating another layer.

print("Horizontal Stack:")
print(h_stack)

print("\nVertical Stack:")
print(v_stack)

print("\nDepth Stack:")
print(d_stack)

Horizontal Stack:
[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

Vertical Stack:
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

Depth Stack:
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [25]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

# This splits joined_array_1 into 2 smaller arrays
# Each smaller array is still two-dimensional because each one still has rows and columns

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [27]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

# This splits joined_array_1 into 3 smaller arrays
# The split is not perfectly even because joined_array_1 has 4 rows
# NumPy still allows it and makes the arrays as evenly sized as possible
# Each result is still two-dimensional

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [ ]:
# This checks every number in arrA
# arrA % 2 == 0 means divide each number by 2 and check if the remainder is 0
# If the number is even, it keeps the original number from arrA
# If it is odd it will replase it with "odd"
result_1 = np.where(arrA % 2 == 0, arrA, "odd")
print(result_1)
# Because "odd" is text, the result was converted into strings so the array can hold both numbers and text

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [ ]:
# sort() will sort the values inside each row from smallest to largest
arrB = np.array([[7, 6], [13, 5], [7, 3]])
arrB_sorted = np.sort(arrB)

print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [31]:
# Adding z = arrB < 7 will check every number in arrB if it is less than 7
# arrC = arrB[z] will use the true or false values from z to filet arrB
print(arrB)
z = arrB < 7
arrC = arrB[z]

print(arrC) # This will print only the values that are less than 7

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [ ]:
print(arrB)
y = arrB >= 7
arrD = arrB[y]

print(arrD)
# Only the numbers greater than or equals to 7 will be printed

[[ 7  6]
 [13  5]
 [ 7  3]]
[ 7 13  7]
