# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
# Create a variable named r_1 that contains a random set of integers between
# 1 and 20 with a size of 2 elements. Print r_1.
r_1 = np.random.randint(1, 21, 2)
# (1, 21, 2) --> start, stop, amount or how many values are needed

print(r_1)

[ 6 15]


In [3]:
# Create a variable named r_2 that contains a random set of integers between
# 1 and 20 with a size of 1 row, 2 columns. Print r_2.
r_2 = np.random.randint(1, 21, size=(1,2))

print(r_2)

[[ 6 13]]


In [10]:
# Create a variable named r_3 that contains a random set of floats between
# 0 and 1 with a size of 2 rows, 1 columns. Print r_3.
r_3 = np.random.random(size=(2,1))

print(r_3)

[[0.46619775]
 [0.44370035]]


In [11]:
# Create a variable named r_4 that contains a random set of integers between
# 20 and 100 with a size of 4 rows, 5 columns. Print r_4.
r_4 = np.random.randint(20, 101, size=(4,5))


print(r_4)

[[45 20 76 35 89]
 [93 81 51 39 66]
 [43 93 75 49 29]
 [50 91 83 26 38]]


In [12]:
# Create a variable named r_5 that contains a random set of floats between
# 0 and 1 with a size of 4 rows, 5 columns. Print r_5.
r_5 = np.random.random(size=(4,5))

print(r_5)

[[0.8255634  0.04962054 0.56026731 0.42600791 0.33829702]
 [0.1643232  0.90015441 0.02565421 0.83642369 0.04234803]
 [0.20491702 0.84995433 0.78239214 0.59902057 0.82930291]
 [0.81613629 0.24142058 0.0515133  0.66776443 0.20794408]]


## Generating Random Choices from an Array

In [13]:
# Create a variable named students and assign it a 1-D array containing the names of 12 of your classmates.
students = np.array([
    "Sharlene", "Cris", "Dania", "Dimitri", "Patrick", "Chantal", "Femi", "Sha'Rya", "Malaika", "Caleb"
])

In [18]:
# Create a variable named call_on and use it to choose one random selection from students. Print call_on.
call_on = np.random.choice(students)

print(call_on)

Dania


In [ ]:
# Create a variable named breakout_groups and use it to choose a random sampling from students that is 3 rows, 4 columns in size.
# Print breakout_groups and examine the results - would this be an effective way to assign breakout groups? Why or why not?
breakout_groups = np.random.choice(students, size=(3, 4))

print(breakout_groups)

# This would not be the best way to assign breakout groups because the same student could be chosen more than once

[['Patrick' 'Sharlene' 'Sharlene' 'Femi']
 ['Cris' 'Cris' 'Malaika' 'Dania']
 ['Cris' 'Cris' 'Caleb' 'Chantal']]


In [25]:
# Create a variable named call_on_weighted and use it to choose make five random selections from students, but this time assign different probability values
# that will determine how likely each student is to be selected. At least one student should have a zero likelihood of being called on, and at least one student should
# have a 30% likelihood of being called on. Distribute other probability values as you choose, and in a comment, explain the p values you assigned to each student. Print call_on_weighted.
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[0, 0.30, 0.10, 0.10, 0.10, 0.10, 0.10, 0.05, 0.05, 0.10]
)

print(call_on_weighted)

# The p values are the probabilities for each student
# The first student has 0 probability, so they will not be selected
# The second student has 0.30 probability, so they are the most likely to be selected
# The other students have smaller probabilities
# All probabilities add up to 1

['Femi' 'Cris' 'Chantal' 'Caleb' 'Cris']


## Generating a Normal Distribution

In [26]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))

print(bell_curve)
# loc=10 means the mean/center is 10
# scale=5 means the standard deviation is 5
# size=(4, 5) means 4 rows and 5 columns

[[15.98823154  6.77423432 14.06793173 13.7230705  14.43773227]
 [13.72620534 10.02561242 11.0151986  19.5930633   8.85546024]
 [10.69790152 24.29633214 10.7977623  19.35888464 10.49006697]
 [12.35685361 13.49008272  8.00990073  0.79240623 15.54776323]]
