# Exercise 1.C Performing operations on arrays

In [33]:
import numpy as np

## Sample Arrays

In [34]:
# Stores 2 random integers
r_1 = np.random.randint(1, 21, 2)

# stores 1 row and 2 columns
r_2 = np.random.randint(1, 21, size=(1, 2))

# stores 2 rows and 1 column of decimals
r_3 = np.random.random(size=(2, 1))

# stores 4 rows and 5 columns of integers
r_4 = np.random.randint(20, 101, size=(4, 5))

# stores 4 rows and 5 columns of decimals
r_5 = np.random.random(size=(4, 5))

print("r_1:")
print(r_1)
print()
print("r_2:")
print(r_2)
print()
print("r_3:")
print(r_3)
print()
print("r_4:")
print(r_4)
print()
print("r_5:")
print(r_5)

r_1:
[ 6 13]

r_2:
[[ 9 20]]

r_3:
[[0.07705647]
 [0.85538988]]

r_4:
[[77 30 93 59 32]
 [64 64 57 95 68]
 [35 42 90 78 70]
 [82 90 56 88 61]]

r_5:
[[0.7168555  0.20812011 0.54176966 0.36232728 0.94372847]
 [0.63675737 0.2711642  0.57706063 0.46344483 0.59516152]
 [0.29735165 0.11278735 0.67725673 0.9613005  0.06641374]
 [0.91717495 0.7576631  0.38544326 0.61538389 0.73281051]]


## Permutations

In [35]:
print("Original r_4:")
print(r_4)

Original r_4:
[[77 30 93 59 32]
 [64 64 57 95 68]
 [35 42 90 78 70]
 [82 90 56 88 61]]


In [36]:
np.random.shuffle(r_4)

print("Shuffled r_4:")
print(r_4)
# Shuffles r_4 directly. It does not create a new copy. It changes the original r_4.

Shuffled r_4:
[[77 30 93 59 32]
 [35 42 90 78 70]
 [64 64 57 95 68]
 [82 90 56 88 61]]


The rows in r_4 were shuffled. The values inside each row stayed together, but the row order changed.

In [37]:
new_shuffle = np.random.permutation(r_4)

print("new_shuffle:")
print(new_shuffle)

print("r_4:")
print(r_4)
# Stores a shuffled copy of r_4. np.random.permutation(r_4) creates a new shuffled version without changing the original r_4.

new_shuffle:
[[64 64 57 95 68]
 [77 30 93 59 32]
 [82 90 56 88 61]
 [35 42 90 78 70]]
r_4:
[[77 30 93 59 32]
 [35 42 90 78 70]
 [64 64 57 95 68]
 [82 90 56 88 61]]


I would use shuffle when I want to change the original array. I would use permutation when I want a shuffled copy but still want to keep the original array the same.

## Mathematical Operations

In [38]:
print("r_1:")
print(r_1)
print("Shape of r_1:", r_1.shape)

print("r_2:")
print(r_2)
print("Shape of r_2:", r_2.shape)

result = np.add(r_1, r_2)

print("r_1 + r_2:")
print(result)
print("Shape of result:", result.shape)
# r_1 has 2 values. r_2 has 1 row and 2 columns. NumPy can match them because both have 2 values across the columns.

r_1:
[ 6 13]
Shape of r_1: (2,)
r_2:
[[ 9 20]]
Shape of r_2: (1, 2)
r_1 + r_2:
[[15 33]]
Shape of result: (1, 2)


In [39]:
print("r_1:")
print(r_1)
print("Shape of r_1:", r_1.shape)

print("r_3:")
print(r_3)
print("Shape of r_3:", r_3.shape)

result = np.add(r_1, r_3)

print("r_1 + r_3:")
print(result)
print("Shape of result:", result.shape)
# This works because r_1 goes across the columns, and r_3 goes down the rows. NumPy stretches them into a 2 by 2 result.

r_1:
[ 6 13]
Shape of r_1: (2,)
r_3:
[[0.07705647]
 [0.85538988]]
Shape of r_3: (2, 1)
r_1 + r_3:
[[ 6.07705647 13.07705647]
 [ 6.85538988 13.85538988]]
Shape of result: (2, 2)


In [40]:
print("r_2:")
print(r_2)
print("Shape of r_2:", r_2.shape)

print("r_4:")
print(r_4)
print("Shape of r_4:", r_4.shape)

np.add(r_2, r_4)
# r_2 + r_4, their shapes do not match, so this will give an error

r_2:
[[ 9 20]]
Shape of r_2: (1, 2)
r_4:
[[77 30 93 59 32]
 [35 42 90 78 70]
 [64 64 57 95 68]
 [82 90 56 88 61]]
Shape of r_4: (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

This gives a ValueError because r_2 has shape (1, 2), but r_4 has shape (4, 5). The last dimensions are 2 and 5, so NumPy cannot broadcast them together.

In [ ]:
# Error tests
np.add(r_1, r_4)

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [ ]:
np.add(r_2, r_4)

ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [ ]:
np.add(r_3, r_4)

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

The error message says the operands could not be broadcast together. This means the array shapes do not match in a way NumPy can stretch.

In [ ]:
np.add(np.array([1]), r_4)
# This added 1 to every value in r_4.

array([[35, 42, 86, 58, 91],
       [33, 91, 47, 42, 53],
       [83, 21, 92, 65, 33],
       [70, 91, 45, 50, 33]])

In [ ]:
np.add(np.array([[1]]), r_4)
# This also added 1 to every value in r_4.

array([[35, 42, 86, 58, 91],
       [33, 91, 47, 42, 53],
       [83, 21, 92, 65, 33],
       [70, 91, 45, 50, 33]])

In [ ]:
np.add(np.array([1, 1, 1, 1, 1]), r_4)
# This worked because the array has 5 values, which matches the 5 columns in r_4.

array([[35, 42, 86, 58, 91],
       [33, 91, 47, 42, 53],
       [83, 21, 92, 65, 33],
       [70, 91, 45, 50, 33]])

In [ ]:
np.add(np.array([[1], [1]]), r_4)
# This gave an error because (2, 1) does not match (4, 5).

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

Broadcasting means NumPy stretches a smaller array so it can work with a bigger array. A single value can be added to every value. A row with 5 values can be added across 5 columns. The resulting shape usually follows the larger array, as long as the smaller array can match or stretch.

## Rounding

In [ ]:
print(r_3)

[[0.63678931]
 [0.86109637]]


In [42]:
print(np.trunc(r_3))
# trunc cuts off the decimal part.

[[0.]
 [0.]]


In [43]:
print(np.fix(r_3))
# fix also moves the number toward zero.

[[0.]
 [0.]]


In [44]:
print(np.floor(r_3))
# floor rounds down.

[[0.]
 [0.]]


In [45]:
print(np.ceil(r_3))
# ceil rounds up.

[[1.]
 [1.]]


In [46]:
print(np.round(r_3, 2))
# rounds each decimal to 2 decimal places.

[[0.08]
 [0.86]]


## Cumulative Operations

In [47]:
print(r_4)

[[77 30 93 59 32]
 [35 42 90 78 70]
 [64 64 57 95 68]
 [82 90 56 88 61]]


In [48]:
print(np.sum(r_4))
# This adds every number in the whole array.

1331


In [49]:
print(np.sum(r_4, axis=0))
# This adds down the columns.

[258 226 296 320 231]


In [50]:
print(np.sum(r_4, axis=1))
# This adds across each row.

[291 315 348 377]


In [51]:
print(np.cumsum(r_4))
# This creates a running total through all values.

[  77  107  200  259  291  326  368  458  536  606  670  734  791  886
  954 1036 1126 1182 1270 1331]


In [52]:
print(np.cumsum(r_4, axis=0))
# This creates a running total going down each column.

[[ 77  30  93  59  32]
 [112  72 183 137 102]
 [176 136 240 232 170]
 [258 226 296 320 231]]


## Grocery Problem

In [63]:
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print("bag1:", bag1)
print("bag2:", bag2)

bag1: [2 3 4 0]
bag2: [4 0 1 2]


In [64]:
# Write an expression to calculate the total number of items in each bag, and print the result in the form of a sentence.
bag_totals = np.sum([bag1, bag2], axis=1)

print(f"The first bag contains {bag_totals[0]} items, and the second bag contains {bag_totals[1]} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [65]:
# Write an expression to calculate the total number of items in each category, and print the result in the form of a sentence.
category_totals = np.add(bag1, bag2)

print(f"There are {category_totals[0]} vegetables, {category_totals[1]} fruits, {category_totals[2]} boxes of snacks, and {category_totals[3]} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [66]:
ali = np.array([5, 4, 6, 4, 2])
ben = np.array([0, 5, 5, 3, 4])
carla = np.array([3, 6, 0, 3, 4])
# Each array stores one person’s door knocks from Monday through Friday. 0 was used for days they missed.

In [67]:
all_knocks = np.array([ali, ben, carla])

print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [69]:
person_totals = np.sum(all_knocks, axis=1)

print("Total doors knocked by each person:")
print(person_totals)
# axis=1 adds across each row, so it gives each person’s weekly total.

Total doors knocked by each person:
[21 17 16]


In [70]:
day_totals = np.sum(all_knocks, axis=0)

print("Total doors knocked each day:")
print(day_totals)
# axis=0 adds down each column, so it gives the group total for each day.

Total doors knocked each day:
[ 8 15 11 10 10]


In [ ]:
rolling_votes = np.floor(np.cumsum(day_totals) / 2)

print("Rolling estimated votes by day:")
print(rolling_votes)
# np.cumsum(day_totals) creates the running total by day. I added floor() to round down to the nearest whole number
# to calculate the estimated number of people who would vote, instead of having decimals like 11.5 which will not make sense
# since we are talking about people. Then / 2 estimates votes because every 2 door-knocks equals 1 vote.

Rolling estimated votes by day:
[ 4. 11. 17. 22. 27.]
